# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MergeFiles(object):
    def setupUi(self, MergeFiles):
        MergeFiles.setObjectName("MergeFiles")
        MergeFiles.resize(372, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(MergeFiles)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(MergeFiles)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mergeButton = QtWidgets.QPushButton(MergeFiles)
        self.mergeButton.setObjectName("mergeButton")
        self.horizontalLayout.addWidget(self.mergeButton)
        self.cancelButton = QtWidgets.QPushButton(MergeFiles)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MergeFiles)
        QtCore.QMetaObject.connectSlotsByName(MergeFiles)

    def retranslateUi(self, MergeFiles):
        _translate = QtCore.QCoreApplication.translate
        MergeFiles.setWindowTitle(_translate("MergeFiles", "Merge Files"))
        self.mergeButton.setText(_translate("MergeFiles", "Merge"))
        self.cancelButton.setText(_translate("MergeFiles", "Cancel"))
